# Write your MySQL query statement below
WITH TEMP1 AS (
SELECT DISTINCT REPORTS_TO AS REPORTING_TO,EMPLOYEE_ID AS REPORTING_EMPLOYEE_ID, NAME AS NAME_REPORTER, AGE AS AGE_REPORTER FROM EMPLOYEES WHERE REPORTS_TO IS NOT NULL )

SELECT DISTINCT A.EMPLOYEE_ID AS employee_id  , A.name AS name  , COUNT(*) AS reports_count , round(AVG(B.AGE_REPORTER),0) AS average_age FROM EMPLOYEES A RIGHT JOIN TEMP1 B ON  B.REPORTING_TO = A.EMPLOYEE_ID  GROUP BY 1,2 order by 1